### ISSUE TITLE
I got this error while running the replit code what should i do

### ISSUE THREAD

**Issue by supergamer4238** [dtomper/Discord-AI-Chatbot#1]
Process Process-1:
Traceback (most recent call last):
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/project-ai-copied-ver/venv/lib/python3.8/site-packages/undetected_chromedriver/dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/subprocess.py", line 1585, in _execute_child
    and os.path.dirname(executable)
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Codeusername78** [comment]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    driver = uc.Chrome(options=chrome_options)
  File "/home/runner/ChatBot/venv/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 57, in __new__
    instance.__init__(*args, **kwargs)
  File "/home/runner/ChatBot/venv/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/runner/ChatBot/venv/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/home/runner/ChatBot/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 101, in start
    self.assert_process_still_running()
  File "/home/runner/ChatBot/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 113, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: 127
I have been getting this problem
Kindly help Dtomper
